<?php

namespace App\Services;

use function Vinsaj9\Crypto\Scrypt\scrypt;

/**
 * Verifies a password against a hash in the Flask app's format
 * (Werkzeug's generate_password_hash(), default method: scrypt).
 * Format: "scrypt:<n>:<r>:<p>$<salt>$<hex digest>".
 *
 * This is deliberately NOT registered as the app's default Hasher.
 * Verified against a real hash generated by werkzeug.security in the
 * Flask app (see the Phase 1 plan) -- byte-for-byte correct, but at
 * Werkzeug's default parameters (n=32768) a pure-PHP implementation
 * (no native scrypt extension is available) takes roughly 15 seconds
 * per check. That's fine for the one-time check this class exists for
 * -- verifying an existing user's password exactly once, immediately
 * followed by rehashing to bcrypt so every later login is fast -- but
 * would make login unusable if it were the ongoing verification path.
 */
class LegacyPasswordHasher
{
    public static function isLegacyHash(string $hash): bool
    {
        return str_starts_with($hash, 'scrypt:');
    }

    public static function verify(string $password, string $hash): bool
    {
        if (! self::isLegacyHash($hash)) {
            return false;
        }

        $parts = explode('$', $hash, 3);
        if (count($parts) !== 3) {
            return false;
        }

        [$method, $salt, $expectedHex] = $parts;
        $methodParts = explode(':', $method);
        if (count($methodParts) !== 4 || $methodParts[0] !== 'scrypt') {
            return false;
        }

        [, $n, $r, $p] = $methodParts;
        $computedHex = scrypt($password, $salt, (int) $n, (int) $r, (int) $p, 64);

        return hash_equals($expectedHex, $computedHex);
    }
}
