<?php

namespace Tests\Unit;

use App\Services\LegacyPasswordHasher;
use PHPUnit\Framework\TestCase;

use function Vinsaj9\Crypto\Scrypt\scrypt;

class LegacyPasswordHasherTest extends TestCase
{
    public function test_is_legacy_hash_recognizes_the_scrypt_prefix(): void
    {
        $this->assertTrue(LegacyPasswordHasher::isLegacyHash('scrypt:32768:8:1$abc$def'));
        $this->assertFalse(LegacyPasswordHasher::isLegacyHash('$2y$12$abcdefghijklmnopqrstuv'));
    }

    /**
     * A small N (16, vs. Werkzeug's real default of 32768) keeps this
     * fast -- it proves the class's format parsing and comparison logic
     * are correct without paying the real, ~15s-per-check cost that
     * only the real N actually incurs (see test_verifies_a_real_hash_
     * generated_by_werkzeug below for that).
     */
    public function test_verifies_a_hash_built_with_a_small_n_for_speed(): void
    {
        $salt = 'testsalt12345678';
        $hex = scrypt('correct-password', $salt, 16, 8, 1, 64);
        $hash = "scrypt:16:8:1\${$salt}\${$hex}";

        $this->assertTrue(LegacyPasswordHasher::verify('correct-password', $hash));
        $this->assertFalse(LegacyPasswordHasher::verify('wrong-password', $hash));
    }

    public function test_rejects_malformed_hashes(): void
    {
        $this->assertFalse(LegacyPasswordHasher::verify('anything', 'not-a-real-hash'));
        $this->assertFalse(LegacyPasswordHasher::verify('anything', 'scrypt:32768:8:1$onlyonepart'));
        $this->assertFalse(LegacyPasswordHasher::verify('anything', 'pbkdf2:sha256:600000$salt$hex'));
    }

    /**
     * The definitive interop proof: a hash generated by this sandbox's
     * actual Flask venv running
     * werkzeug.security.generate_password_hash('CorrectHorseBatteryStaple123!')
     * -- byte-for-byte real output, not a guess at the format. Slow
     * (~15s) by nature of Werkzeug's real N=32768 parameter and no
     * native scrypt extension being available; that's the whole reason
     * this class exists only for a one-time check during login, with
     * an immediate rehash to bcrypt afterward (see AuthenticatedSessionController).
     *
     * @group slow
     */
    public function test_verifies_a_real_hash_generated_by_werkzeug(): void
    {
        $hash = 'scrypt:32768:8:1$PbcK1KHkd6K5Ia73$487630c2a9296c351ee181fa965132bc36354d1f4f17a38ae6298e48a2010a600e04d7f5d8d02be414245c139823f70f60250ff51c4448a3ebd2478a9a424fac';

        $this->assertTrue(LegacyPasswordHasher::verify('CorrectHorseBatteryStaple123!', $hash));
        $this->assertFalse(LegacyPasswordHasher::verify('wrong-password', $hash));
    }
}
